import os
from fastapi import FastAPI, UploadFile, File, HTTPException
from typing import List, Optional
from pydantic import BaseModel
from shared.models import Audit, Certificate, AccessLevel, StabilityProfile, CausalEffects, DriftAlert
from google import genai
from google.genai import types
from datetime import datetime
import uuid

app = FastAPI(title="FairGuard Backend", version="1.0.0")

# In-memory storage for demo
audits = {}
certificates = {}

@app.get("/healthz")
async def healthz():
    return {"status": "ok", "timestamp": datetime.now().isoformat()}

@app.post("/audit/dataset")
async def audit_dataset(file: UploadFile = File(...), protected_attributes: List[str] = [], model_id: Optional[str] = "gemini-2.0-flash"):
    audit_id = str(uuid.uuid4())
    # Mock audit logic
    audit = Audit(
        id=audit_id,
        targetModel="demo-model",
        datasetName=file.filename,
        accessLevel=AccessLevel.BB,
        protectedAttributes=protected_attributes,
        stability=StabilityProfile(grade="B", perturbationScore=0.85, scenarioResults={"noise": 0.9, "outliers": 0.8}),
        causal=CausalEffects(ctfDE=0.05, ctfIE=0.02, ctfSE=0.01, totalVariation=0.08, confidenceInterval=(0.04, 0.06)),
        drift_history=[],
        modelId=model_id,
        timestamp=datetime.now().isoformat()
    )
    audits[audit_id] = audit
    return audit

@app.post("/audit/llm")
async def audit_llm(scenario_template: str, endpoint_url: str):
    # Mock LLM audit
    return {"status": "started", "audit_id": str(uuid.uuid4())}

@app.post("/audit/stability")
async def audit_stability(audit_id: str):
    return {"status": "running", "audit_id": audit_id}

@app.post("/audit/certify")
async def audit_certify(audit_id: str, model_id: Optional[str] = None):
    if audit_id not in audits:
        raise HTTPException(status_code=404, detail="Audit not found")
    
    audit = audits[audit_id]
    active_model = model_id or audit.modelId or "gemini-2.0-flash"
    
    # 1. Create a mock certificate result
    cert_data = {
        "auditId": audit_id,
        "verdict": "CERTIFIED_FAIR",
        "overallStabilityGrade": audit.stability.grade,
        "worstAffectedGroup": "Young Professionals (20-25)",
        "disparityMagnitude": 0.042,
        "remediationAction": "Implement causal-aware reweighting in the preprocessing pipeline.",
        "accessLevel": audit.accessLevel,
        "causalFindings": audit.causal.model_dump(),
        "regulatoryCompliance": [
            {"regulation": "EU AI Act Article 9 & 15", "status": "PASS", "justification": "Transparency measures meet high-risk AI criteria."},
            {"regulation": "NYC Local Law 144", "status": "PASS", "justification": "Impact ratio variance is within the 0.8 four-fifths threshold."},
            {"regulation": "Colorado SB21-169", "status": "PASS", "justification": "External testing for proxy variables confirmed non-discriminatory outcome."}
        ],
        "modelId": active_model,
        "signature": f"FAIRGUARD-SIG-{uuid.uuid4().hex[:12].upper()}",
        "timestamp": datetime.now().isoformat()
    }

    # 2. Generate report using chosen model
    api_key = os.getenv("GEMINI_API_KEY")
    # For a real implementation, we would route based on active_model
    # If active_model is "gemma-2-9b" and we have a custom provider, we'd use that.
    # For now, we'll use Gemini but prefix the report to show it's "aware" of the model choice.
    
    if api_key:
        try:
            from backend.report.prompt_templates import REPORT_PROMPT
            client = genai.Client(api_key=api_key)
            
            prompt = f"{REPORT_PROMPT}\n\n[SYSTEM NOTE: AUDITOR MODEL IS {active_model}]\n\nCONTEXT (Certificate JSON):\n{cert_data}"
            
            # Route to appropriate Gemini model if active_model matches a Gemini alias
            # Otherwise use a default
            target_model = active_model if "gemini" in active_model.lower() else "gemini-2.0-flash"
            
            response = client.models.generate_content(
                model=target_model,
                contents=prompt
            )
            report_text = response.text
            cert_data["generated_report"] = f"Generated by {active_model}:\n\n{report_text}"
        except Exception as e:
            print(f"Model generation error: {e}")
            cert_data["generated_report"] = f"Report generation failed for {active_model}. Using raw data."

    cert = Certificate(**cert_data)
    certificates[audit_id] = cert
    return cert

@app.get("/certificate/{audit_id}")
async def get_certificate(audit_id: str):
    if audit_id not in certificates:
        raise HTTPException(status_code=404, detail="Certificate not found")
    return certificates[audit_id]

@app.get("/drift/{audit_id}/history")
async def get_drift_history(audit_id: str):
    return audits.get(audit_id, {}).get("drift_history", [])

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000)
